name: Execute Paper Trades

on:
  schedule:
    # Run every 5 minutes during market hours: 9:15 AM - 3:30 PM IST = 3:45 AM - 10:00 AM UTC (Monday-Friday)
    - cron: '*/5 3-9 * * 1-5'  # Every 5 minutes from 3:45-9:59 UTC (Mon-Fri)
    - cron: '*/5 10 * * 1-5'    # Every 5 minutes at 10:00 UTC (Mon-Fri) - market close
  workflow_dispatch:
    inputs:
      timeframes:
        description: 'Timeframes to execute trades for (comma-separated)'
        required: true
        default: '1m,5m,15m'
        type: string
      confidence:
        description: 'Minimum confidence threshold'
        required: true
        default: '0.7'
        type: string
      dry_run:
        description: 'Run in dry-run mode'
        required: false
        default: false
        type: boolean

jobs:
  execute-trades:
    runs-on: ubuntu-latest
    steps:
      - name: Check market hours and holidays
        id: market-check
        run: |
          # Get current UTC time
          UTC_HOUR=$(date -u +%H)
          UTC_MIN=$(date -u +%M)
          DAY_OF_WEEK=$(date -u +%u)  # 1=Monday, 7=Sunday

          # Convert to IST (UTC + 5:30)
          IST_HOUR=$(( (UTC_HOUR + 5) % 24 ))
          IST_MIN=$(( UTC_MIN + 30 ))

          # Handle minute overflow
          if [ $IST_MIN -ge 60 ]; then
            IST_MIN=$(( IST_MIN - 60 ))
            IST_HOUR=$(( (IST_HOUR + 1) % 24 ))
          fi

          echo "Current UTC: $(date -u +'%Y-%m-%d %H:%M:%S')"
          echo "Current IST: $(printf "%02d:%02d" $IST_HOUR $IST_MIN)"
          echo "Day of week: $DAY_OF_WEEK (1=Monday, 7=Sunday)"

          # Check if it's a weekday (1-5 = Monday-Friday)
          if [ "$DAY_OF_WEEK" -lt 1 ] || [ "$DAY_OF_WEEK" -gt 5 ]; then
            echo "⚠️ Weekend detected. Skipping execution."
            echo "market_open=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Check if within market hours (IST 9:15 AM - 3:30 PM)
          if [ "$IST_HOUR" -lt 9 ] || [ "$IST_HOUR" -gt 15 ]; then
            if [ "$IST_HOUR" -eq 9 ] && [ "$IST_MIN" -lt 15 ]; then
              echo "⚠️ Before market opens (9:15 AM IST). Skipping execution."
              echo "market_open=false" >> $GITHUB_OUTPUT
              exit 0
            fi
            if [ "$IST_HOUR" -eq 15 ] && [ "$IST_MIN" -gt 30 ]; then
              echo "⚠️ After market closes (3:30 PM IST). Skipping execution."
              echo "market_open=false" >> $GITHUB_OUTPUT
              exit 0
            fi
            echo "⚠️ Outside market hours. Skipping execution."
            echo "market_open=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "✅ Market is open. Proceeding with trade execution."
          echo "market_open=true" >> $GITHUB_OUTPUT

      - name: Execute Paper Trades
        if: steps.market-check.outputs.market_open == 'true'
        run: |
          # Set default values
          TIMEFRAMES="${{ github.event.inputs.timeframes || '1m,5m,15m,1h,1d' }}"
          CONFIDENCE="${{ github.event.inputs.confidence || '0.7' }}"
          DRY_RUN="${{ github.event.inputs.dry_run || 'false' }}"

          echo "Executing paper trades for timeframes: $TIMEFRAMES"
          echo "Confidence threshold: $CONFIDENCE"
          echo "Dry run: $DRY_RUN"

          # Split timeframes and execute for each
          IFS=',' read -ra TF_ARRAY <<< "$TIMEFRAMES"
          for TF in "${TF_ARRAY[@]}"; do
            TF=$(echo "$TF" | xargs)  # Trim whitespace
            echo "=== Processing timeframe: $TF ==="

            if [ "$DRY_RUN" = "true" ]; then
              python apps/api/auto_execute_signals.py --tf "$TF" --confidence "$CONFIDENCE" --dry-run
            else
              python apps/api/auto_execute_signals.py --tf "$TF" --confidence "$CONFIDENCE"
            fi

            echo "Completed processing for $TF"
            echo ""
          done