name: Nightly Backtest

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  backtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r ml/requirements.txt
          pip install supabase
      - name: Run backtests and register model
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          API_BASE: ${{ secrets.API_BASE }}
          SCANNER_TOKEN: ${{ secrets.SCANNER_TOKEN }}
        run: |
          OUT=$(python ml/run_backtests.py)
          echo "$OUT"
          VERSION=$(echo "$OUT" | python -c "import sys,json; print(json.load(sys.stdin)['version'])")
          PARAMS=$(echo "$OUT" | python -c "import sys,json; print(json.dumps(json.load(sys.stdin)['params']))")
          METRICS=$(echo "$OUT" | python -c "import sys,json; print(json.dumps(json.load(sys.stdin)['metrics']))")
          curl -sS -X POST "$API_BASE/ai/models/register" -H "Authorization: Bearer $SCANNER_TOKEN" -H "Content-Type: application/json" -d "{\"version\":\"$VERSION\",\"params\":$PARAMS,\"metrics\":$METRICS}" || true


