name: Scan 1m

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Call scanner 1m
        run: |
          curl -sS -X POST "https://aitradingapp.onrender.com/scanner/run?mode=1m"


