name: Scan 1m

on:
  schedule:
    # Market hours: 9:15 AM - 3:30 PM IST = 3:45 AM - 10:00 AM UTC (Monday-Friday)
    - cron: '45-59 3 * * 1-5'  # 3:45-3:59 UTC (Mon-Fri)
    - cron: '*/1 4-9 * * 1-5'  # 4:00-9:59 UTC (Mon-Fri)
    - cron: '*/1 10 * * 1-5'   # 10:00 UTC (Mon-Fri) - market close
  workflow_dispatch:

jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check market hours and holidays
        id: market-check
        run: |
          # Get current UTC time
          UTC_HOUR=$(date -u +%H)
          UTC_MIN=$(date -u +%M)
          DAY_OF_WEEK=$(date -u +%u)  # 1=Monday, 7=Sunday

          # Convert to IST (UTC + 5:30)
          IST_HOUR=$(( (UTC_HOUR + 5) % 24 ))
          IST_MIN=$(( UTC_MIN + 30 ))

          # Handle minute overflow
          if [ $IST_MIN -ge 60 ]; then
            IST_MIN=$(( IST_MIN - 60 ))
            IST_HOUR=$(( (IST_HOUR + 1) % 24 ))
          fi

          echo "Current UTC: $(date -u +'%Y-%m-%d %H:%M:%S')"
          echo "Current IST: $(printf "%02d:%02d" $IST_HOUR $IST_MIN)"
          echo "Day of week: $DAY_OF_WEEK (1=Monday, 7=Sunday)"

          # Check if it's a weekday (1-5 = Monday-Friday)
          if [ "$DAY_OF_WEEK" -lt 1 ] || [ "$DAY_OF_WEEK" -gt 5 ]; then
            echo "⚠️ Weekend detected. Skipping scan."
            echo "market_open=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Check if within market hours (IST 9:15 AM - 3:30 PM)
          if [ "$IST_HOUR" -lt 9 ] || [ "$IST_HOUR" -gt 15 ]; then
            if [ "$IST_HOUR" -eq 9 ] && [ "$IST_MIN" -lt 15 ]; then
              echo "⚠️ Before market opens (9:15 AM IST). Skipping scan."
              echo "market_open=false" >> $GITHUB_OUTPUT
              exit 0
            fi
            if [ "$IST_HOUR" -eq 15 ] && [ "$IST_MIN" -gt 30 ]; then
              echo "⚠️ After market closes (3:30 PM IST). Skipping scan."
              echo "market_open=false" >> $GITHUB_OUTPUT
              exit 0
            fi
            echo "⚠️ Outside market hours. Skipping scan."
            echo "market_open=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "✅ Market is open. Proceeding with scan."
          echo "market_open=true" >> $GITHUB_OUTPUT

      - name: Call scanner 1m
        if: steps.market-check.outputs.market_open == 'true'
        run: |
          curl -sS -X POST "https://aitradingapp.onrender.com/scanner/run?mode=1m"