name: Scan 5m

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Call scanner 5m
        env:
          API_BASE: ${{ secrets.API_BASE }}
          SCANNER_TOKEN: ${{ secrets.SCANNER_TOKEN }}
        run: |
          curl -sS -X POST "$API_BASE/scanner/run?mode=5m" -H "Authorization: Bearer $SCANNER_TOKEN" || true


