name: Scan 5m

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Call scanner 5m
        run: |
          curl -sS -X POST "https://aitradingapp.onrender.com/scanner/run?mode=5m"


