name: Scan 15m

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Call scanner 15m
        run: |
          curl -sS -X POST "https://aitradingapp.onrender.com/scanner/run?mode=15m"


