name: Scan 1m

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Call scanner 1m
        env:
          API_BASE: ${{ secrets.API_BASE }}
          SCANNER_TOKEN: ${{ secrets.SCANNER_TOKEN }}
        run: |
          curl -sS -X POST "$API_BASE/scanner/run?mode=1m" -H "Authorization: Bearer $SCANNER_TOKEN" || true


