name: Weekly Retrain

on:
  schedule:
    - cron: '0 19 * * 0'
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r ml/requirements.txt
          pip install supabase requests
      - name: RL tuning update
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          API_BASE: ${{ secrets.API_BASE }}
          SCANNER_TOKEN: ${{ secrets.SCANNER_TOKEN }}
        run: |
          python ml/rl_tuner.py


